name: build_and_tests
run-name: Checking current build + tests

on  :
    push:
        branches:
            - release
    pull_request:
        types: [opened, reopened]
        branches:
            - release

jobs:
    check-build:
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v4
        
            - uses: actions/setup-node@v4
              with:
                node-version: '20' 
        
            - name: Install dependencies for CI
              run : npm ci

            - name: Build project
              run : npm run build

    check-tests:
        needs: [check-build]
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20' 

            - name: Install dependencies for CI
              run : npm ci

            #- name: Linter
            #  run : |
            #    chmod +x ./.github/scripts/strict-linter.sh
            #    ./.github/scripts/strict-linter.sh

            - name: Run Jest tests
              run : npm run test

            - if  : ${{ failure() }}
              run : |
                echo "Rejecting action. Either the tests or the linter failed"
                exit 0